version: "3"
services:
  web:
    build: .
    ports:
     - 8888:8888
     - 8000:8000
    image: web-jobs:1
    depends_on:
      - db
  db:
    image: postgres:10.3
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432