package lv.robertsv.speedment.test.webjobs.public_.scheduled_job;

import com.speedment.Entity;
import com.speedment.field.ComparableField;
import com.speedment.field.StringField;
import com.speedment.internal.core.field.ComparableFieldImpl;
import com.speedment.internal.core.field.StringFieldImpl;
import java.util.Optional;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the
 * com.speedment.internal.ui.config.TableProperty@2e10fb13.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface ScheduledJob extends Entity<ScheduledJob> {
    
    /**
     * This Field corresponds to the {@link ScheduledJob} field that can be
     * obtained using the {@link ScheduledJob#getId()} method.
     */
    public final static ComparableField<ScheduledJob, Long> ID = new ComparableFieldImpl<>("id", ScheduledJob::getId, ScheduledJob::setId);
    /**
     * This Field corresponds to the {@link ScheduledJob} field that can be
     * obtained using the {@link ScheduledJob#getPath()} method.
     */
    public final static StringField<ScheduledJob> PATH = new StringFieldImpl<>("path", ScheduledJob::getPath, ScheduledJob::setPath);
    /**
     * This Field corresponds to the {@link ScheduledJob} field that can be
     * obtained using the {@link ScheduledJob#getSchedule()} method.
     */
    public final static StringField<ScheduledJob> SCHEDULE = new StringFieldImpl<>("schedule", ScheduledJob::getSchedule, ScheduledJob::setSchedule);
    /**
     * This Field corresponds to the {@link ScheduledJob} field that can be
     * obtained using the {@link ScheduledJob#getStatus()} method.
     */
    public final static StringField<ScheduledJob> STATUS = new StringFieldImpl<>("status", ScheduledJob::getStatus, ScheduledJob::setStatus);
    /**
     * This Field corresponds to the {@link ScheduledJob} field that can be
     * obtained using the {@link ScheduledJob#getEnabled()} method.
     */
    public final static ComparableField<ScheduledJob, Integer> ENABLED = new ComparableFieldImpl<>("enabled", o -> o.getEnabled().orElse(null), ScheduledJob::setEnabled);
    
    /**
     * Returns the id of this ScheduledJob. The id field corresponds to the
     * database column webjobs.public.scheduled_job.id.
     * 
     * @return the id of this ScheduledJob
     */
    Long getId();
    
    /**
     * Returns the path of this ScheduledJob. The path field corresponds to the
     * database column webjobs.public.scheduled_job.path.
     * 
     * @return the path of this ScheduledJob
     */
    String getPath();
    
    /**
     * Returns the schedule of this ScheduledJob. The schedule field corresponds
     * to the database column webjobs.public.scheduled_job.schedule.
     * 
     * @return the schedule of this ScheduledJob
     */
    String getSchedule();
    
    /**
     * Returns the status of this ScheduledJob. The status field corresponds to
     * the database column webjobs.public.scheduled_job.status.
     * 
     * @return the status of this ScheduledJob
     */
    String getStatus();
    
    /**
     * Returns the enabled of this ScheduledJob. The enabled field corresponds to
     * the database column webjobs.public.scheduled_job.enabled.
     * 
     * @return the enabled of this ScheduledJob
     */
    Optional<Integer> getEnabled();
    
    /**
     * Sets the id of this ScheduledJob. The id field corresponds to the database
     * column webjobs.public.scheduled_job.id.
     * 
     * @param id to set of this ScheduledJob
     * @return this ScheduledJob instance
     */
    ScheduledJob setId(Long id);
    
    /**
     * Sets the path of this ScheduledJob. The path field corresponds to the
     * database column webjobs.public.scheduled_job.path.
     * 
     * @param path to set of this ScheduledJob
     * @return this ScheduledJob instance
     */
    ScheduledJob setPath(String path);
    
    /**
     * Sets the schedule of this ScheduledJob. The schedule field corresponds to
     * the database column webjobs.public.scheduled_job.schedule.
     * 
     * @param schedule to set of this ScheduledJob
     * @return this ScheduledJob instance
     */
    ScheduledJob setSchedule(String schedule);
    
    /**
     * Sets the status of this ScheduledJob. The status field corresponds to the
     * database column webjobs.public.scheduled_job.status.
     * 
     * @param status to set of this ScheduledJob
     * @return this ScheduledJob instance
     */
    ScheduledJob setStatus(String status);
    
    /**
     * Sets the enabled of this ScheduledJob. The enabled field corresponds to
     * the database column webjobs.public.scheduled_job.enabled.
     * 
     * @param enabled to set of this ScheduledJob
     * @return this ScheduledJob instance
     */
    ScheduledJob setEnabled(Integer enabled);
}