package lv.robertsv.speedment.test;

import com.speedment.internal.core.runtime.ApplicationMetadata;
import javax.annotation.Generated;

/**
 * A {@link com.speedment.internal.core.runtime.ApplicationMetadata} class
 * for the {@link com.speedment.config.Project} named test. This class
 * contains the meta data present at code generation time.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class TestApplicationMetadata implements ApplicationMetadata {
    
    private final static StringBuilder METADATA = new StringBuilder();
    
    static {
        METADATA.append("import com.speedment.config.parameters.*\n");
        METADATA.append("\n");
        METADATA.append("name = \"test\";\n");
        METADATA.append("packageLocation = \"src/main/java\";\n");
        METADATA.append("packageName = \"lv.robertsv.speedment\";\n");
        METADATA.append("enabled = true;\n");
        METADATA.append("expanded = true;\n");
        METADATA.append("dbms {\n");
        METADATA.append("    ipAddress = \"127.0.0.1\";\n");
        METADATA.append("    name = \"webjobs\";\n");
        METADATA.append("    port = 5432;\n");
        METADATA.append("    typeName = \"PostgreSQL\";\n");
        METADATA.append("    username = \"postgres\";\n");
        METADATA.append("    enabled = true;\n");
        METADATA.append("    expanded = true;\n");
        METADATA.append("    schema {\n");
        METADATA.append("        columnCompressionType = ColumnCompressionType.NONE;\n");
        METADATA.append("        fieldStorageType = FieldStorageType.WRAPPER;\n");
        METADATA.append("        name = \"public\";\n");
        METADATA.append("        schemaName = \"public\";\n");
        METADATA.append("        storageEngineType = StorageEngineType.ON_HEAP;\n");
        METADATA.append("        defaultSchema = false;\n");
        METADATA.append("        enabled = true;\n");
        METADATA.append("        expanded = true;\n");
        METADATA.append("        table {\n");
        METADATA.append("            columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("            fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("            name = \"scheduled_job\";\n");
        METADATA.append("            storageEngineType = StorageEngineType.INHERIT;\n");
        METADATA.append("            tableName = \"scheduled_job\";\n");
        METADATA.append("            enabled = true;\n");
        METADATA.append("            expanded = true;\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                databaseType = java.lang.Long.class;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"id\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.LongIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                expanded = true;\n");
        METADATA.append("                nullable = false;\n");
        METADATA.append("            }\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                databaseType = java.lang.String.class;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"path\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                expanded = true;\n");
        METADATA.append("                nullable = false;\n");
        METADATA.append("            }\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                databaseType = java.lang.String.class;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"schedule\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                expanded = true;\n");
        METADATA.append("                nullable = false;\n");
        METADATA.append("            }\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                databaseType = java.lang.String.class;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"status\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                expanded = true;\n");
        METADATA.append("                nullable = false;\n");
        METADATA.append("            }\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                databaseType = java.lang.Integer.class;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"enabled\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.IntegerIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                expanded = true;\n");
        METADATA.append("                nullable = true;\n");
        METADATA.append("            }\n");
        METADATA.append("        }\n");
        METADATA.append("    }\n");
        METADATA.append("}\n");
    }
    
    @Override
    public String getMetadata() {
        return METADATA.toString();
    }
}