package lv.robertsv.speedment.test;

import com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle;
import javax.annotation.Generated;
import lv.robertsv.speedment.test.webjobs.public_.scheduled_job.impl.ScheduledJobManagerImpl;

/**
 * A {@link
 * com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle} class
 * for the {@link com.speedment.config.Project} named test.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class TestApplication extends SpeedmentApplicationLifecycle<TestApplication> {
    
    public TestApplication() {
        setSpeedmentApplicationMetadata(new TestApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        super.onInit();
        loadAndSetProject();
        put(new ScheduledJobManagerImpl(speedment));
    }
}